name: "Publish to Docker"
description: "Pushes built artifacts to Docker"

inputs:
  registry_username:
    description: "Username for image registry"
    required: true
  registry_password:
    description: "Password for image registry"
    required: true

runs:
  using: "composite"
  steps:
    - name: Dependant is Running
      shell: bash
      run: hello from composite
#    - uses: docker/setup-buildx-action@v1
#    - uses: docker/login-action@v1
#      with:
#        username: ${{inputs.registry_username}}
#        password: ${{inputs.registry_password}}
#
#    - name: 🐳 Login to DockerHub
#      uses: docker/login-action@v3
#      with:
##       registry: ghcr.io
#        username: ${{ secrets.CI_REGISTRY_USER }}
#        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
#
#    - name: 🐳 Build and push
#      uses: docker/build-push-action@v5
#      env:
#        CI_REGISTRY_USER: "romdhanisamir"
#        DOCKER_IMAGE_NAME: demo_app
#        DOCKER_IMAGE_TAG: github-action-ci_${{ GITHUB_RUN_NUMBER }}
#      with:
#        context: .
#        push: true
#        tags: $CI_REGISTRY_USER/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}:latest, $CI_REGISTRY_USER/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
#      run: |
#        chmod +x -R ./scripts/build-environments.sh && ./scripts/build-environments.sh
