name: "Publish to Docker"
description: "Pushes built artifacts to Docker"

inputs:
  registry_username:
    description: "Username for image registry"
    required: true
  registry_password:
    description: "Password for image registry"
    required: true
  working_directory:
    description: "Git context of Dockerfile"
    required: true
  docker_image_name:
    description: "Docker image name"
    required: true
  github_run_number:
    description: "github run number"
    required: false

outputs:
  docker_image:
    description: "Docker image name with tag"
    value: ${{ steps.docker_image_with_tag.outputs.docker_image }}

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: 🐳 Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: 🐳 Build and Push latest
      uses: docker/build-push-action@v5
      env:
        DOCKER_IMAGE_TAG: github-action-ci-${{ inputs.github_run_number }}
      with:
        context: ${{inputs.working_directory}}
        file: ${{inputs.working_directory}}/Dockerfile
        push: true
        tags: ${{ inputs.registry_username }}/${{ inputs.docker_image_name }}:${{ env.DOCKER_IMAGE_TAG }}, ${{ inputs.registry_username }}/${{ inputs.docker_image_name }}:latest

    - name: docker image with tag
      id: docker_image_with_tag
      run: echo "docker_image=${{ inputs.docker_image_name }}:github-action-ci-${{ inputs.github_run_number }}" >> $GITHUB_OUTPUT
      shell: bash