apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-github-deploy
  namespace: cncf-tn
spec:
  replicas: 15
  selector:
    matchLabels:
      app: demo
      ci: github-actions
  template:
    metadata:
      labels:
        app: demo
        ci: github-actions
    spec:
      containers:
      - name: app
        image: romdhanisamir/demo_app:github-action-ci-28
        ports:
        - containerPort: 80
        imagePullPolicy: Always
